# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow @ 12:12 AM every Sunday
  schedule:
    - cron: '12 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
          #token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Scrape and commit
        run: |
          echo Scraping db
          ./scrape.sh

          # if there are no changes, exit early
          git diff --exit-code HEAD && exit 0

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "github actions scrape commit ${{ steps.date.outputs.DATE }}"
          git push --set-upstream origin main
          git tag ${{ steps.date.outputs.date }}
          git push origin ${{ steps.date.outputs.date }}
